### ISSUE TITLE
Update Extension for Pale Moon v27

### ISSUE THREAD

**Issue by prikhi** [Pale-Moon-Addons-Team/pentadactyl-pm#3]
Plugin is broken in the latest version of Pale Moon. I tried fixing a few errors printed to the console when starting up, but those lead to a large cascade of errors. There's a couple methods that have been removed(`XUL.quote()`, `NS.quote()`) & there's a bunch of "redeclaration arguments" errors.

I'll be poking around and will push a WIP branch to my fork if I make a reasonable amount of progress.

There's a forum thread about it here:
https://forum.palemoon.org/viewtopic.php?t=13755

**Comment by Lootyhoof** [comment]
Thanks for looking into this! Patches would be very much welcome if you manage to find a fix. :)

**Comment by prikhi** [comment]
Is there an upgrade guide for addons? I've been blindly setting references to `document` to `window.document` instead. Can `document` refer to something other than `window.document`?

I'm also getting a ton of errors like this:
```
Timestamp: 11/24/2016 11:57:06 PM
Error: [Exception... "Could not convert JavaScript argument arg 0 [nsISupports.QueryInterface]"  nsresult: "0x80570009 (NS_ERROR_XPC_BAD_CONVERT_JS)"  location: "JS frame :: resource://dactyl/bootstrap.jsm -> resource://dactyl/buffer.jsm :: Buffer<.contentViewer :: line 204"  data: no]
Source File: resource://dactyl/bootstrap.jsm -> resource://dactyl/util.jsm
Line: 1375
```
And I have no idea to handle it.

This is incomplete & rough, I'll probably have to redo it more thoroughly(once I have a better understanding of what the old `document` could potentially refer to):
https://github.com/prikhi/pentadactyl-pm/tree/pm-27-upgrade-test-1

**Comment by bulldozer2003** [comment]
:money_mouth_face: 
I put this up as a bounty on bountysource for anyone who fixes pentadactyl to work with palemoon v27:
https://www.bountysource.com/trackers/19509551-pale-moon-addons-team-pentadactyl-pm

I also started a bounty on updating pentadactyl to a WebExtension to work in Firefox 57+:
https://www.bountysource.com/trackers/4405414-5digits-dactyl

Please contribute to either if you can.

**Comment by prikhi** [comment]
I'm going to try to resume work on this sometime this week

**Comment by madand** [comment]
I ported Pentadactyl to Pale Moon 27: https://github.com/madand/pentadactyl-pm

However, I cannot make a PR with the actual code against this repo, because my code is a fork of upstream dactyl and this repo is based on contents of some legacy snapshot XPI file. So I created #5 which just updates the README, yet formally solves the issue :smile:

**Comment by prikhi** [comment]
@madand Awesome! Will test it out soon.

It'd be nice to be able to install this from the palemoon addons site, @Lootyhoof is it possible to set that up with madand's fork or does the repo need to belong to Pale-Moon-Addons-Team?

**Comment by prikhi** [comment]
@madand I think to make a PR, you'd have to rename your repo, fork this repo, then merge your repo into the fork using the `--allow-unrelated-histories` flag.

**Comment by madand** [comment]
@prikhi I think your solution is way too brutal, just imagine PR with 7k commits in it :rofl:. Fun aside, the main drawback, as I see it, will be the lost fork relationship from upstream dactyl repo.

I propose another solution:
* Rename this repo to `Pale-Moon-Addons-Team/pentadactyl-pm-26`.
* Fork my repo without any history rewrites.

**Comment by Lootyhoof** [comment]
I think ultimately it depends who would be up for maintaining this if need be. So far it's lived in `Pale-Moon-Addons-Team` as kind of an umbrella for anyone who might want to throw a patch at it, and admittedly it hasn't received much love over the years.

If someone is up for maintaining it more frequently then I think it would be best left in their care rather than here.

**Comment by madand** [comment]
Since it is now based on the upstream master, the frequency of updates is up to the actual Pentadactyl maintainers. And its development was rather slow lately. I am completely unfamiliar with XUL development and Pentadactly codebase is rather big, so backporting/testing is all I can do for this project.

I will maintain my repo for the time being, so let it be the upstream for PM27 port. As of this repo, I guess mergin #5 would be enough.

The other question is about publishing XPIs on https://addons.palemoon.org/. How can I publish anything there?

For now, I will publish new XPIs via Github releases after every meaningful fix or backport. The drawback is that Pale Moon will not be able to automatically update the extension, so proper publishing is desirable for sure.

**Comment by Lootyhoof** [comment]
Thanks for the confirmation! I'll be in touch shortly on the forums about getting it on the site.

**Comment by wolfbeast** [comment]
Since I was the one originally hacking this together: if you made a new fork for pentadactyl on Pale Moon then I'm overjoyed to be able to hand this off to you. All I did was "make it work" with absolutely no guarantees of future support or maintenance. I'll rename this repo and make a clear statement to that effect (and probably eventually delete it)
